import { STAFF_ROLES } from '../../config/roles';
import { EMOJIS } from '../../config/emojis';

export const COACH_ROLE_IDS = {
    STAFF: STAFF_ROLES.ADMIN,
    COACH: '1459057859777134633',
} as const;

export const COACH_CHANNEL_IDS = {
    TRAINING_CATEGORY: '1459056237147852872',
    EMBED_CHANNEL: '1459057344007770246',
    TICKET_CATEGORY: '1459056711296880701',
    REQUESTS_CHANNEL: '1459057439289638984',
    COACHES_DISPLAY_CHANNEL: '1459068214616129578',
    LEAVE_COACH_CHANNEL: '1460403628035543140',
} as const;

export const COACH_CONFIG = {
    embedColor: '#9B59B6',
    footerText: 'AUGE — o topo do competitivo.',
} as const;

export const COACH_CUSTOM_IDS = {
    REQUEST_COACH_BUTTON: 'coach_request_button',
    FILL_FORM_BUTTON: 'coach_fill_form',
    FORM_MODAL: 'coach_form_modal',
    FORM_GAME_STYLE: 'coach_form_game_style',
    FORM_TEACHING_STYLE: 'coach_form_teaching_style',
    FORM_PLATFORM: 'coach_form_platform',
    FORM_FPS: 'coach_form_fps',
    FORM_PING: 'coach_form_ping',
    FORM_AVAILABILITY: 'coach_form_availability',
    FORM_EXPERIENCE: 'coach_form_experience',
    FORM_MAIN: 'coach_form_main',
    FORM_CONEXAO: 'coach_form_conexao',
    MAIN_MODAL: 'coach_main_modal',
    ACCEPT_STUDENT: 'coach_accept_student',
    REJECT_STUDENT: 'coach_reject_student',
    PROFILE_MODAL: 'coach_profile_modal',
    PROFILE_GAME_STYLE: 'coach_profile_game_style',
    PROFILE_TEACHING_STYLE: 'coach_profile_teaching_style',
    PROFILE_MAIN: 'coach_profile_main',
    PROFILE_PLATFORM: 'coach_profile_platform',
    PROFILE_AVAILABILITY: 'coach_profile_availability',
    SELECT_GAME_STYLE: 'coach_select_game_style',
    SELECT_TEACHING_STYLE: 'coach_select_teaching_style',
    SELECT_PLATFORM: 'coach_select_platform',
    SELECT_AVAILABILITY: 'coach_select_availability',
    SELECT_EXPERIENCE: 'coach_select_experience',
    START_FORM_BUTTON: 'coach_start_form',
    CLOSE_TICKET_BUTTON: 'coach_close_ticket',
    BTN_GAME_STYLE: 'coach_btn_game_',
    BTN_TEACHING_STYLE: 'coach_btn_teaching_',
    BTN_PLATFORM: 'coach_btn_platform_',
    BTN_AVAILABILITY: 'coach_btn_avail_',
    BTN_EXPERIENCE: 'coach_btn_exp_',
    BTN_CONFIRM_AVAILABILITY: 'coach_btn_confirm_avail',
    LEAVE_COACH_BUTTON: 'coach_leave_',
    LEAVE_CONFIRM_YES: 'coach_leave_yes_',
    LEAVE_CONFIRM_NO: 'coach_leave_no_',
    LEAVE_COACH_GENERAL: 'coach_leave_general',
} as const;

export const COACH_MESSAGES = {
    EMBED_TITLE: `${EMOJIS.SETINHA_ROXA} TREINADORES DA AUGE`,
    EMBED_DESCRIPTION: [
        `${EMOJIS.PONTO_ROXO} Quer evoluir e representar a AUGE no topo?`,
        '',
        `${EMOJIS.SHIELD} **Nossos treinadores vão te ajudar a:**`,
        `${EMOJIS.PONTO_ROXO} Desenvolver seu estilo de jogo`,
        `${EMOJIS.PONTO_ROXO} Dominar seu main`,
        `${EMOJIS.PONTO_ROXO} Virar um jogador de elite`,
        '',
        `${EMOJIS.USERS} **Como funciona:**`,
        `${EMOJIS.PONTO_ROXO} Clica no botão abaixo`,
        `${EMOJIS.PONTO_ROXO} Abre um ticket privado`,
        `${EMOJIS.PONTO_ROXO} Preenche o formulário`,
        `${EMOJIS.PONTO_ROXO} A gente te conecta com o treinador ideal`,
        '',
        `${EMOJIS.BANZADA} **Vagas limitadas por treinador!**`,
    ].join('\n'),
    REQUEST_BUTTON: '⚔️ Quero ser Treinado',
    TICKET_WELCOME: '👋 Salve! Bem-vindo ao sistema de treinamento da AUGE!\n\nPreenche o formulário abaixo pra gente te encaixar com o treinador certo.',
    FILL_FORM_BUTTON: '📋 Preencher Formulário',
    START_FORM_BUTTON: '🚀 Bora Começar',
    CLOSE_TICKET_BUTTON: '🔒 Finalizar Ticket',
    CONV_GAME_STYLE: [
        `${EMOJIS.SETINHA_ROXA} **Pergunta 1/7 — Estilo de Jogo**`,
        '',
        'Qual estilo de jogo tu quer desenvolver?',
        '',
        `${EMOJIS.PONTO_ROXO} **Agressivo** → Pressão constante, rush, dominar o ritmo da partida`,
        `${EMOJIS.PONTO_ROXO} **Passivo** → Contra-ataque, esperar o momento certo pra agir`,
        `${EMOJIS.PONTO_ROXO} **Equilibrado** → Saber adaptar conforme a situação do jogo`,
        `${EMOJIS.PONTO_ROXO} **Clutch** → Especialista em x1 e situações de pressão`,
    ].join('\n'),
    CONV_TEACHING_STYLE: [
        `${EMOJIS.SETINHA_ROXA} **Pergunta 2/7 — Tipo de Treinador**`,
        '',
        'Qual estilo de treinador combina mais contigo?',
        '',
        `${EMOJIS.PONTO_ROXO} **Rígido** → Cobra muito, exige perfeição, não aceita erro`,
        `${EMOJIS.PONTO_ROXO} **Calmo** → Vai no teu ritmo, tem paciência, ensina devagar`,
        `${EMOJIS.PONTO_ROXO} **Direto** → Fala na lata, sem enrolação, objetivo`,
        `${EMOJIS.PONTO_ROXO} **Motivador** → Foco em incentivar, sempre positivo`,
    ].join('\n'),
    CONV_PLATFORM: [
        `${EMOJIS.SETINHA_ROXA} **Pergunta 3/7 — Plataforma**`,
        '',
        'Tu joga em qual plataforma?',
        '',
        `*Isso ajuda o treinador a entender melhor tua gameplay e dar dicas específicas.*`,
    ].join('\n'),
    CONV_AVAILABILITY: [
        `${EMOJIS.SETINHA_ROXA} **Pergunta 4/7 — Disponibilidade**`,
        '',
        'Quais horários tu tá disponível pra treinar?',
        '',
        `*Seleciona todos que tu puder e depois clica em **Confirmar**.*`,
    ].join('\n'),
    CONV_EXPERIENCE: [
        `${EMOJIS.SETINHA_ROXA} **Pergunta 5/7 — Experiência**`,
        '',
        'Qual tua experiência no Death Ball?',
        '',
        `${EMOJIS.PONTO_ROXO} **Iniciante** → Menos de 1 mês jogando, ainda aprendendo o básico`,
        `${EMOJIS.PONTO_ROXO} **Intermediário** → 1 a 6 meses, já sabe jogar mas quer melhorar`,
        `${EMOJIS.PONTO_ROXO} **Avançado** → 6+ meses, quer refinar e dominar técnicas avançadas`,
    ].join('\n'),
    CONV_MAIN_CHARACTER: [
        `${EMOJIS.SETINHA_ROXA} **Pergunta 6/7 — Personagem Principal**`,
        '',
        'Qual teu **main**? (personagem que tu mais joga)',
        '',
        `*Se tu ainda não tem um main definido, pode escrever "não tenho" ou o que tu mais usa.*`,
        '',
        `${EMOJIS.PONTO_ROXO} **Clica no botão abaixo pra informar:**`,
    ].join('\n'),
    CONV_FPS_PING: [
        `${EMOJIS.SETINHA_ROXA} **Pergunta 7/7 — Conexão e Lag**`,
        '',
        'Última pergunta! Preciso saber sobre tua conexão.',
        '',
        `*FPS, Ping e se tu costuma jogar lagado. Seja sincero, isso ajuda o treinador a entender tuas limitações.*`,
        '',
        `${EMOJIS.PONTO_ROXO} **Clica no botão abaixo pra informar:**`,
    ].join('\n'),
    FORM_TITLE: '⚔️ Treinamento AUGE',
    FORM_GAME_STYLE_LABEL: 'Estilo de jogo que quer desenvolver',
    FORM_TEACHING_STYLE_LABEL: 'Tipo de treinador que prefere',
    FORM_PLATFORM_LABEL: 'Plataforma',
    FORM_FPS_LABEL: 'Quantos FPS você joga?',
    FORM_PING_LABEL: 'Qual seu ping médio?',
    FORM_AVAILABILITY_LABEL: 'Disponibilidade de horário',
    FORM_EXPERIENCE_LABEL: 'Experiência no jogo',
    FORM_SUBMITTED: '✅ Formulário enviado!\n\n⏳ Aguarde! Um treinador da AUGE será designado pra você em breve.',
    STUDENT_ACCEPTED: '🎉 Treinador designado!\n\n⚔️ {coach} será seu treinador na AUGE!\n\nEle vai entrar em contato contigo pra começar os treinos.\n\nBora representar! ⚔️',
    STUDENT_REJECTED: '❌ Sua solicitação foi recusada.\n\nVocê pode tentar novamente clicando no botão no canal de solicitação.',
    CHANNEL_WELCOME: '⚔️ **TREINAMENTO AUGE** ⚔️\n\n🎓 **Treinador:** {coach}\n👥 **Alunos:** {students}\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━\nEste canal é exclusivo pra vocês organizarem os treinos.\n\nBora pra cima! ⚔️',
    ERROR_NOT_COACH: '❌ Você não é um treinador.',
    ERROR_NOT_STAFF: '❌ Você não tem permissão para usar este comando.',
    ERROR_COACH_NOT_FOUND: '❌ Treinador não encontrado.',
    ERROR_ALREADY_COACH: '❌ Este usuário já é um treinador.',
    ERROR_STUDENT_NOT_FOUND: '❌ Aluno não encontrado.',
    ERROR_REQUEST_NOT_FOUND: '❌ Solicitação não encontrada.',
    ERROR_ALREADY_ACCEPTED: '❌ Esta solicitação já foi aceita.',
    ERROR_NO_PROFILE: '❌ Você ainda não configurou seu perfil. Use `/treinador perfil` primeiro.',
    SUCCESS_COACH_ADDED: '✅ **{user}** foi adicionado como treinador!\n\n📁 Canal criado: {channel}\n🏷️ Cargo criado: {role}',
    SUCCESS_COACH_REMOVED: '✅ **{user}** foi removido do sistema de treinadores.',
    SUCCESS_STUDENT_REMOVED: '✅ **{user}** foi removido da sua lista de alunos.',
    SUCCESS_PROFILE_UPDATED: '✅ Seu perfil foi atualizado com sucesso!',
    SUCCESS_SETUP: '✅ Embed de treinadores enviado com sucesso!',
    LEAVE_BUTTON: 'Sair do Treinador',
    LEAVE_CONFIRM_TITLE: `${EMOJIS.SHIELD} Tem certeza?`,
    LEAVE_CONFIRM_DESC: [
        `${EMOJIS.PONTO_ROXO} Você está prestes a **sair do treinamento** com {coach}.`,
        '',
        `${EMOJIS.SETINHA_ROXA} **O que vai acontecer:**`,
        `${EMOJIS.PONTO_ROXO} Você perderá acesso ao canal de treino`,
        `${EMOJIS.PONTO_ROXO} Poderá escolher outro treinador no canal de tickets`,
        `${EMOJIS.PONTO_ROXO} Seu novo treinador precisará aceitar você`,
        '',
        '**Deseja continuar?**'
    ].join('\n'),
    LEAVE_SUCCESS: `${EMOJIS.SHIELD} Você saiu do treinamento com **{coach}**!\n\n${EMOJIS.PONTO_ROXO} Você pode solicitar um novo treinador no canal de tickets.`,
    LEAVE_CANCELLED: `${EMOJIS.PONTO_ROXO} Operação cancelada. Você continua com seu treinador atual.`,
    LEAVE_NOT_STUDENT: `${EMOJIS.PONTO_ROXO} Você não é aluno deste treinador.`,
    LEAVE_NO_COACH: `${EMOJIS.PONTO_ROXO} Você não está treinando com nenhum treinador no momento.`,
    LEAVE_EMBED_TITLE: `${EMOJIS.SETINHA_ROXA} SAIR DO TREINAMENTO`,
    LEAVE_EMBED_DESC: [
        `${EMOJIS.PONTO_ROXO} Quer trocar de treinador ou parar o treinamento?`,
        '',
        `${EMOJIS.SHIELD} **Como funciona:**`,
        `${EMOJIS.PONTO_ROXO} Clica no botão abaixo`,
        `${EMOJIS.PONTO_ROXO} Confirma que quer sair`,
        `${EMOJIS.PONTO_ROXO} Seu acesso ao canal de treino será removido`,
        `${EMOJIS.PONTO_ROXO} Você pode solicitar outro treinador quando quiser`,
        '',
        `${EMOJIS.USERS} **Atenção:**`,
        `${EMOJIS.PONTO_ROXO} Só aparece opção se você tiver um treinador`,
        `${EMOJIS.PONTO_ROXO} Seu novo treinador vai precisar te aceitar novamente`,
    ].join('\n'),
} as const;

export const COACH_IMAGE = 'https://cdn.discordapp.com/attachments/1441261270459482235/1460406082395443250/a7010d0c5a38634ed065c269679e7fcd.gif?ex=6966cca7&is=69657b27&hm=8ffd0cc4c09a96f7d816a588991019b3b145d0b6ec2629b227df73e09ade8448';

export const COACH_TICKET_GIF = 'https://cdn.discordapp.com/attachments/1441261270459482235/1460406082395443250/a7010d0c5a38634ed065c269679e7fcd.gif?ex=6966cca7&is=69657b27&hm=8ffd0cc4c09a96f7d816a588991019b3b145d0b6ec2629b227df73e09ade8448';

export const COACH_LEAVE_GIF = 'https://cdn.discordapp.com/attachments/1441261270459482235/1460406027832004772/32d0acd772ae82a24c7594646a6d9e62.gif?ex=6966cc9a&is=69657b1a&hm=4ff88f8bf51bbe59e48b0852c282edf8290a1eedbc587428c1fbacd706f254c4';
